version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: budgetgame:latest 
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    networks:
      - bgnet
  mongo:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: budgetgame
    #   MONGO_INITDB_ROOT_PASSWORD: budgetgamepass
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo/mongod.conf:/etc/mongod.conf
      - ./.docker/mongo/db/:/data/db
      - ./.docker/mongo/log/:/var/log/mongodb/
      - ./mongodumps/neworleans:/tmp/neworleans
    command: ["-f", "/etc/mongod.conf"]
    networks:
      - bgnet
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on: 
      - app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bgnet

networks:
  bgnet:
    driver: bridge
